### PR TITLE
Blog app: Add forms

### PR DESCRIPTION
**Pull request by mohisa302**
### Add forms
In this PR I:

- Added Comment and Like controller
- Added partial view to post
- Added a like button and Added comment button
- Saved the changes in the database

### CODE REVIEW

**Review by mwanawabangona — CHANGES_REQUESTED** [review]
Hi @mohisa302,

Good job so far!

There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights
* ✅  No linter errors :heavy_check_mark:
* ✅  Repo looks professional :briefcase:
* ✅  Good quality commits


## Required Changes ♻️
_Check the comments under the review._

- [ ]  Amazing working so far 👏 👏 
- [ ] However, the code you provided raises a "PG::DuplicateColumn" error indicating that the 'users' table already has a column named 'posts_counter'; please review the code and remove the redundant column creation.
- [ ] Please see the screenshot below

image


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mohisa302** [comment]
Dear @

> Hi @mohisa302,
> 
> Good job so far!  There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * ✅  No linter errors ✔️
> * ✅  Repo looks professional 💼
> * ✅  Good quality commits
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]   Amazing working so far 👏 👏
> * [ ]  However, the code you provided raises a "PG::DuplicateColumn" error indicating that the 'users' table already has a column named 'posts_counter'; please review the code and remove the redundant column creation.
> * [ ]  Please see the screenshot below
> 
> image
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider: N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Dear @mwanawabangona , thanks for your review, could you please mention which command i can check there is no kind of error more?

**Comment by mohisa302** [comment]
Dear @

> Hi @mohisa302,
> 
> Good job so far!  There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * ✅  No linter errors ✔️
> * ✅  Repo looks professional 💼
> * ✅  Good quality commits
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]   Amazing working so far 👏 👏
> * [ ]  However, the code you provided raises a "PG::DuplicateColumn" error indicating that the 'users' table already has a column named 'posts_counter'; please review the code and remove the redundant column creation.
> * [ ]  Please see the screenshot below
> 
> image
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider: N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Dear @mwanawabangona , thanks for your review, could you please mention with which command I can check if there is no kind of error?

**Comment by mohisa302** [comment]
Dear @

> Hi @mohisa302,
> 
> Good job so far!  There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * ✅  No linter errors ✔️
> * ✅  Repo looks professional 💼
> * ✅  Good quality commits
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]   Amazing working so far 👏 👏
> * [ ]  However, the code you provided raises a "PG::DuplicateColumn" error indicating that the 'users' table already has a column named 'posts_counter'; please review the code and remove the redundant column creation.
> * [ ]  Please see the screenshot below
> 
> image
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider: N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Dear @mwanawabangona , thanks for your review, could you please mention with which command I can check if there is no kind of error?

**Comment by mohisa302** [comment]
Dear @

> Hi @mohisa302,
> 
> Good job so far!  There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * ✅  No linter errors ✔️
> * ✅  Repo looks professional 💼
> * ✅  Good quality commits
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]   Amazing working so far 👏 👏
> * [ ]  However, the code you provided raises a "PG::DuplicateColumn" error indicating that the 'users' table already has a column named 'posts_counter'; please review the code and remove the redundant column creation.
> * [ ]  Please see the screenshot below
> 
> image
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider: N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Dear @mwanawabangona , thanks for your review, could you please mention with which command I can check if there is no kind of error?

**Comment by mohisa302** [comment]
Dear @

> Hi @mohisa302,
> 
> Good job so far!  There are some issues that you still need to work on to go to the next project but you are almost there!
> 
> ## Highlights
> * ✅  No linter errors ✔️
> * ✅  Repo looks professional 💼
> * ✅  Good quality commits
> 
> ## Required Changes ♻️
> _Check the comments under the review._
> 
> * [ ]   Amazing working so far 👏 👏
> * [ ]  However, the code you provided raises a "PG::DuplicateColumn" error indicating that the 'users' table already has a column named 'posts_counter'; please review the code and remove the redundant column creation.
> * [ ]  Please see the screenshot below
> 
> image
> 
> ## Optional suggestions
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
> You can also consider: N/A
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Dear @mwanawabangona , thanks for your review, could you please mention with which command I can check if there is no kind of error?

**Comment by mohisa302** [comment]
> Dear @
> 
> > Hi @mohisa302,
> > Good job so far!  There are some issues that you still need to work on to go to the next project but you are almost there!
> > ## Highlights
> > 
> > * ✅  No linter errors ✔️
> > * ✅  Repo looks professional 💼
> > * ✅  Good quality commits
> > 
> > ## Required Changes ♻️
> > _Check the comments under the review._
> > 
> > * [ ]    Amazing working so far 👏 👏
> > * [ ]   However, the code you provided raises a "PG::DuplicateColumn" error indicating that the 'users' table already has a column named 'posts_counter'; please review the code and remove the redundant column creation.
> > * [ ]   Please see the screenshot below
> > 
> > image
> > ## Optional suggestions
> > _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> > You can also consider: N/A
> > Cheers and Happy coding!👏👏👏
> > Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> > **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> > _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
> 
> Dear @mwanawabangona , thanks for your review, could you please mention with which command I can check if there is no kind of error?

Dear @mwanawabangona  thanks for your review, could you please guide me with which command I can check if there is no error like this?

**Review by Munsa1 — APPROVED** [review]
Hi @mohisa302, 
congratulations-1

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Requested Changes :heavy_check_mark: 


## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
